export interface Destination {
  id: string;
  name: string;
  slug: string;
  region: string;
  categoryTags: ('nature' | 'heritage' | 'spiritual' | 'honeymoon')[];
  tagline: string;
  description: string;
  heroImage: string;
  thumbnail: string;
  bestTime: string;
  idealDuration: string;
  highlights: string[];
  featuredTop?: boolean;
}

export interface DayItinerary {
  day: number;
  title: string;
  subheading?: string;
  description: string;
  activities: string[];
  meals?: string;
  stay?: string;
  overnight: string;
}

export interface PackageTour {
  id: string;
  title: string;
  slug: string;
  duration: string; // e.g., '4D / 3N'
  days: number;
  nights: number;
  route: string;
  primaryDestinationTags: string[]; // e.g. ['Delhi', 'Agra']
  categories: ('nature' | 'heritage' | 'spiritual' | 'honeymoon')[];
  summary: string;
  heroImage: string;
  highlightTags: string[];
  itinerary: DayItinerary[];
  inclusions: string[];
  exclusions: string[];
  faqs: { question: string; answer: string }[];
  operationalNotes?: string[];
  featured?: boolean;
}

export interface CategoryInfo {
  id: 'nature' | 'heritage' | 'spiritual' | 'honeymoon';
  title: string;
  headline: string;
  description: string;
  thumbnail: string;
}

export const COMPANY_DETAILS = {
  name: 'Lobo Travels',
  tagline: 'Journeys Crafted Around You',
  subheading: 'Bespoke, private itineraries across India crafted with obsessive attention to detail, verified stays, and round-the-clock on-trip care.',
  address: 'Shop No. 12, NDMC Market, Near CNG Pump, Mandir Marg, New Delhi – 110001',
  pincode: '110001',
  email: 'info@lobotravels.com',
  phones: [
    { number: '9811240072', label: 'Bookings & Custom Plans', display: '+91 98112 40072' },
    { number: '9891240072', label: 'Customer Support Desk', display: '+91 98912 40072' },
    { number: '9312640072', label: 'WhatsApp & Fast Enquiry', display: '+91 93126 40072', isWhatsApp: true },
  ],
  whatsappNumber: '919312640072',
  hours: 'Mon – Sat: 9:30 AM – 7:30 PM | Sun: By Appointment (24x7 active tour helpline for on-trip guests)',
  stats: [
    { label: 'Years of Craftsmanship', value: '30+' },
    { label: 'Curated Travelers', value: '28,500+' },
    { label: 'Handcrafted Destinations', value: '22+' },
    { label: 'Direct Trust Rating', value: '4.9 ★' },
  ],
};

export const CATEGORIES: CategoryInfo[] = [
  {
    id: 'nature',
    title: 'Nature & Mountains',
    headline: 'High Passes, Pine Ridges & Alpine Serenity',
    description: 'Crisp mountain air, misty pine valleys, and private riverbank stays across Himachal, Uttarakhand, and the Himalayas.',
    thumbnail: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'heritage',
    title: 'Heritage & History',
    headline: 'Imperial Fortresses, Royal Havelis & Living Legacies',
    description: 'Walk through royal dynasties, sandstone citadels, and timeless architecture with private historian guides.',
    thumbnail: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'spiritual',
    title: 'Spiritual',
    headline: 'Sacred Confluences, Temple Chants & Inner Peace',
    description: 'Witness transcendent evening Ganga Aartis, sacred pilgrimages, and ancient river ghats with serene, respectful logistics.',
    thumbnail: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'honeymoon',
    title: 'Honeymoon',
    headline: 'Intimate Retreats, Candlelit Evenings & Private Vistas',
    description: 'Luxury heritage palace suites, private Kashmiri houseboats, and snow-dusted hill retreats curated for two.',
    thumbnail: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=800&q=80',
  },
];

export const DESTINATIONS: Destination[] = [
  {
    id: 'delhi',
    name: 'Delhi',
    slug: 'delhi',
    region: 'North India (Capital Territory)',
    categoryTags: ['heritage'],
    tagline: 'Imperial Capital of Dynasties, Sufi Sanctuaries & Tree-Lined Boulevards',
    description: 'From Mughal sandstone bastions and fragrant Old Delhi spice alleys to Lutyens’ regal avenues and serene Sufi shrines, Delhi is India’s cultural compass.',
    heroImage: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1600&q=85',
    thumbnail: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=600&q=80',
    bestTime: 'October to March',
    idealDuration: '2 to 3 Days',
    highlights: ['Red Fort & Jama Masjid', 'Humayun’s Tomb & Qutub Minar', 'Kartavya Path & India Gate', 'Chandni Chowk Culinary Walks'],
    featuredTop: true,
  },
  {
    id: 'jaipur',
    name: 'Jaipur',
    slug: 'jaipur',
    region: 'Rajasthan',
    categoryTags: ['heritage'],
    tagline: 'The Pink City: Terracotta Facades, Hilltop Forts & Royal Courtyards',
    description: 'Amber Fort glowing under golden sunlight, geometric wonders at Jantar Mantar, and hand-block artisan ateliers in the heart of royal Rajasthan.',
    heroImage: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1600&q=85',
    thumbnail: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=600&q=80',
    bestTime: 'September to March',
    idealDuration: '3 Days',
    highlights: ['Amber Fort & Sheesh Mahal', 'Hawa Mahal & City Palace', 'Jhalana Leopard Safari', 'Private Jeweler & Textile Studios'],
    featuredTop: true,
  },
  {
    id: 'manali',
    name: 'Manali',
    slug: 'manali',
    region: 'Himachal Pradesh',
    categoryTags: ['nature', 'honeymoon'],
    tagline: 'Snowbound Passes, Cedar Glades & Alpine Solitude',
    description: 'Where the Pir Panjal ranges meet apple orchards and rushing mountain rivers. Enjoy Solang Valley alpine meadows, ancient wood temples, and cozy fireside stays.',
    heroImage: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1600&q=85',
    thumbnail: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=600&q=80',
    bestTime: 'Year-round (Snow in Dec–Feb, Flowers in Apr–Jun)',
    idealDuration: '3 to 4 Days',
    highlights: ['Solang Valley & Rohtang Pass', 'Hadimba Devi Cedar Temple', 'Old Manali Riverside Cafés', 'Vashisht Natural Sulphur Springs'],
    featuredTop: true,
  },
  {
    id: 'shimla',
    name: 'Shimla',
    slug: 'shimla',
    region: 'Himachal Pradesh',
    categoryTags: ['nature', 'honeymoon'],
    tagline: 'Colonial Hill Capital, The Ridge & Misty Himalayan Horizons',
    description: 'Winding ridge strolls, historic neo-Gothic Christ Church, and crisp pine-scented mountain air that defined India’s historic summer retreat.',
    heroImage: 'https://images.unsplash.com/photo-1597074866923-dc0589150358?auto=format&fit=crop&w=1600&q=85',
    thumbnail: 'https://images.unsplash.com/photo-1597074866923-dc0589150358?auto=format&fit=crop&w=600&q=80',
    bestTime: 'March to June & November to February',
    idealDuration: '2 to 3 Days',
    highlights: ['The Ridge & Mall Road', 'Kufri Himalayan Panorama', 'Christ Church & Gaiety Theatre', 'Jakhoo Hill Pine Forest Walks'],
    featuredTop: true,
  },
  {
    id: 'agra',
    name: 'Agra',
    slug: 'agra',
    region: 'Uttar Pradesh',
    categoryTags: ['heritage'],
    tagline: 'The Monument to Love & Red Sandstone Mughal Palaces',
    description: 'The peerless white marble symmetry of the Taj Mahal at sunrise, accompanied by the formidable bastions of Agra Fort and forgotten Fatehpur Sikri.',
    heroImage: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1600&q=85',
    thumbnail: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=600&q=80',
    bestTime: 'October to March',
    idealDuration: '1 to 2 Days',
    highlights: ['Taj Mahal Private Sunrise Visit', 'Agra Fort Mughal Quarters', 'Mehtab Bagh Sunset Vantage', 'Fatehpur Sikri Royal Complex'],
    featuredTop: true,
  },
  {
    id: 'mussoorie',
    name: 'Mussoorie',
    slug: 'mussoorie',
    region: 'Uttarakhand',
    categoryTags: ['nature'],
    tagline: 'Queen of the Hills: Colonial Promenades & Doon Valley Vistas',
    description: 'Perched along a horseshoe ridge in the Garhwal Himalayas, Mussoorie charms travelers with Camel’s Back road walks, Kempty cascades, and panoramic snow peaks.',
    heroImage: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=1600&q=85',
    thumbnail: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=600&q=80',
    bestTime: 'March to June & September to November',
    idealDuration: '2 to 3 Days',
    highlights: ['Gun Hill Cable Car Views', 'Kempty Falls Excursions', 'Library Bazaar Heritage Stroll', 'Company Garden Flora'],
  },
  {
    id: 'nainital',
    name: 'Nainital',
    slug: 'nainital',
    region: 'Uttarakhand',
    categoryTags: ['nature'],
    tagline: 'Emerald Lake Haven Framed by Kumaon Mountain Summits',
    description: 'Centred around the shimmering mango-shaped Naini Lake, this beloved Kumaon hill station offers tranquil boating, ropeway mountain views, and Tibetan market crafts.',
    heroImage: 'https://images.unsplash.com/photo-1610484826967-09c5720778c7?auto=format&fit=crop&w=1600&q=85',
    thumbnail: 'https://images.unsplash.com/photo-1610484826967-09c5720778c7?auto=format&fit=crop&w=600&q=80',
    bestTime: 'March to June & October to February',
    idealDuration: '2 to 3 Days',
    highlights: ['Naini Lake Yacht & Boat Rides', 'Snow View Aerial Ropeway', 'Naina Devi Temple', 'Eco Cave Gardens'],
  },
  {
    id: 'bhimtal',
    name: 'Bhimtal',
    slug: 'bhimtal',
    region: 'Uttarakhand',
    categoryTags: ['nature'],
    tagline: 'Serene Island Lake & Kumaon Lakeside Solitude',
    description: 'A quieter, more contemplative counterpart to Nainital, featuring a massive natural lake with an island aquarium, bordered by quiet pine woods and neighboring Sattal.',
    heroImage: 'https://images.unsplash.com/photo-1506197603052-3cc9c3a201bd?auto=format&fit=crop&w=1600&q=85',
    thumbnail: 'https://images.unsplash.com/photo-1506197603052-3cc9c3a201bd?auto=format&fit=crop&w=600&q=80',
    bestTime: 'March to July & September to December',
    idealDuration: '2 Days',
    highlights: ['Central Island Aquarium', 'Sattal Seven-Lake Forest Circuit', 'Naukuchiatal Nine-Cornered Lake', 'Birdwatching Nature Trails'],
  },
  {
    id: 'jim-corbett',
    name: 'Jim Corbett',
    slug: 'jim-corbett',
    region: 'Uttarakhand',
    categoryTags: ['nature'],
    tagline: 'India’s Legendary Tiger Country & Sal Forest Wilderness',
    description: 'Dense sal and teak forests hugging the Ramganga River, home to Royal Bengal tigers, wild elephant herds, and luxury jungle lodges under starry skies.',
    heroImage: 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=1600&q=85',
    thumbnail: 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=600&q=80',
    bestTime: 'November to June',
    idealDuration: '2 to 3 Days',
    highlights: ['Dhikala & Bijrani Safari Zones', 'Ramganga Riverside Stays', 'Birding in Corbett Foothills', 'Private Naturalist Drives'],
  },
  {
    id: 'kashmir',
    name: 'Kashmir',
    slug: 'kashmir',
    region: 'Jammu & Kashmir',
    categoryTags: ['nature', 'honeymoon'],
    tagline: 'Paradise on Earth: Cedar Houseboats, Saffron Meadows & Glacial Glades',
    description: 'Drifting gently on Dal Lake aboard intricately carved cedar wood houseboats, walking through Mughal chinar gardens, and ascending Gulmarg’s alpine snow slopes.',
    heroImage: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=1600&q=85',
    thumbnail: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=600&q=80',
    bestTime: 'April to October (Tulips & Greenery) & Dec to Feb (Snow)',
    idealDuration: '5 to 7 Days',
    highlights: ['Luxury Houseboat Stays on Dal Lake', 'Gulmarg Gondola Ride', 'Pahalgam Betaab Valley', 'Mughal Gardens of Srinagar'],
  },
  {
    id: 'udaipur',
    name: 'Udaipur',
    slug: 'udaipur',
    region: 'Rajasthan',
    categoryTags: ['heritage', 'honeymoon'],
    tagline: 'City of Lakes: Floating Marble Palaces & Golden Sunset Waters',
    description: 'The romantic capital of Mewar, where white marble palaces rise directly out of Lake Pichola against the soft silhouettes of the Aravalli hills.',
    heroImage: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=1600&q=85',
    thumbnail: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=600&q=80',
    bestTime: 'September to March',
    idealDuration: '3 Days',
    highlights: ['City Palace Complex', 'Lake Pichola Sunset Cruise', 'Jag Mandir Island Palace', 'Saheliyon-ki-Bari Fountains'],
  },
  {
    id: 'jodhpur',
    name: 'Jodhpur',
    slug: 'jodhpur',
    region: 'Rajasthan',
    categoryTags: ['heritage'],
    tagline: 'The Blue City & the Mighty Mehrangarh Cliff Citadel',
    description: 'Indigo-washed houses clustered beneath the towering sheer ramparts of Mehrangarh Fort, with bustling spice bazaars and desert royalty.',
    heroImage: 'https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?auto=format&fit=crop&w=1600&q=85',
    thumbnail: 'https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?auto=format&fit=crop&w=600&q=80',
    bestTime: 'October to March',
    idealDuration: '2 to 3 Days',
    highlights: ['Mehrangarh Fort Ramparts', 'Jaswant Thada Marble Memorial', 'Blue City Heritage Walk', 'Umaid Bhawan Palace'],
  },
  {
    id: 'jaisalmer',
    name: 'Jaisalmer',
    slug: 'jaisalmer',
    region: 'Rajasthan',
    categoryTags: ['heritage'],
    tagline: 'The Golden City: Living Sandstone Fort & Thar Desert Dunes',
    description: 'Rising from the golden sands of the Thar Desert, Jaisalmer features a living medieval fort, delicate stone filigree jharokhas, and luxury desert glamping.',
    heroImage: 'https://images.unsplash.com/photo-1598890777032-bde835ba27c2?auto=format&fit=crop&w=1600&q=85',
    thumbnail: 'https://images.unsplash.com/photo-1598890777032-bde835ba27c2?auto=format&fit=crop&w=600&q=80',
    bestTime: 'October to March',
    idealDuration: '2 to 3 Days',
    highlights: ['Golden Fort (Sonar Qila)', 'Patwon Ki Haveli Filigree', 'Sam Sand Dunes Camel Safari', 'Desert Starlit Glamping'],
  },
  {
    id: 'amritsar',
    name: 'Amritsar',
    slug: 'amritsar',
    region: 'Punjab',
    categoryTags: ['heritage', 'spiritual'],
    tagline: 'Sacred Sanctum of the Golden Temple & Patriotic Reverence',
    description: 'The spiritual heart of Sikhism, radiating universal harmony at the gilded Sri Harmandir Sahib, flanked by Jallianwala Bagh and the electric Wagah Border ceremony.',
    heroImage: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&w=1600&q=85',
    thumbnail: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&w=600&q=80',
    bestTime: 'October to March',
    idealDuration: '2 Days',
    highlights: ['Golden Temple (Harmandir Sahib)', 'Langar Community Kitchen Experience', 'Wagah Border Beating Retreat', 'Jallianwala Bagh Memorial'],
  },
  {
    id: 'haridwar-rishikesh',
    name: 'Haridwar–Rishikesh',
    slug: 'haridwar-rishikesh',
    region: 'Uttarakhand',
    categoryTags: ['spiritual'],
    tagline: 'Spiritual Gateway to the Himalayas & Yoga Capital of the World',
    description: 'Sacred Ganga Aartis illuminating Har Ki Pauri ghats, suspension footbridges swinging over turquoise mountain waters, and serene ashram retreats in Rishikesh.',
    heroImage: 'https://images.unsplash.com/photo-1518002171953-a080ee817e1f?auto=format&fit=crop&w=1600&q=85',
    thumbnail: 'https://images.unsplash.com/photo-1518002171953-a080ee817e1f?auto=format&fit=crop&w=600&q=80',
    bestTime: 'September to May',
    idealDuration: '3 Days',
    highlights: ['Har Ki Pauri Evening Ganga Aarti', 'Ram Jhula & Laxman Jhula', 'Beatles Ashram & Parmarth Niketan', 'Sacred Triveni Ghat Ceremonies'],
  },
  {
    id: 'badrinath-kedarnath',
    name: 'Badrinath–Kedarnath',
    slug: 'badrinath-kedarnath',
    region: 'Uttarakhand',
    categoryTags: ['spiritual'],
    tagline: 'The Glacial Abodes of Shiva & Vishnu in High Garhwal',
    description: 'High in the mist-crowned Garhwal Himalayas, two of Hinduism’s holiest shrines command devotion against towering glaciers and alpine waterfalls.',
    heroImage: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1600&q=85',
    thumbnail: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=600&q=80',
    bestTime: 'May to June & September to October (Seasonal Opening)',
    idealDuration: '6 to 8 Days',
    highlights: ['Kedarnath Jyotirlinga Glacier Trek/Heli', 'Badrinath Temple & Tapt Kund', 'Mana – India’s First Village', 'Vasudhara High Altitude Falls'],
  },
  {
    id: 'yamunotri',
    name: 'Yamunotri',
    slug: 'yamunotri',
    region: 'Uttarakhand',
    categoryTags: ['spiritual'],
    tagline: 'Source of the Sacred River Yamuna in the High Himalayas',
    description: 'Nestled in the western Garhwal Himalayas at 3,293 meters, Yamunotri marks the pristine origin of Goddess Yamuna amidst natural thermal sulphur springs.',
    heroImage: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1600&q=85',
    thumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
    bestTime: 'May to June & September to October',
    idealDuration: '3 to 4 Days (Char Dham circuit)',
    highlights: ['Yamunotri Temple Shrine', 'Surya Kund Boiling Spring', 'Divya Shila Sacred Rock', 'Trek along Yamuna River Gorge'],
  },
  {
    id: 'gangotri',
    name: 'Gangotri',
    slug: 'gangotri',
    region: 'Uttarakhand',
    categoryTags: ['spiritual'],
    tagline: 'The Origin of Mother Ganga Amid Granite Peaks',
    description: 'White granite temple set against silver firs and soaring deodars, where King Bhagiratha’s penance brought the holy river Ganga down to earth.',
    heroImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1600&q=85',
    thumbnail: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=600&q=80',
    bestTime: 'May to June & September to October',
    idealDuration: '3 to 4 Days',
    highlights: ['Gangotri White Granite Temple', 'Bhagirath Shila Sacred Stone', 'Suraj Kund Cascade', 'Gaumukh Glacier Viewpoint Trek'],
  },
  {
    id: 'vaishno-devi',
    name: 'Vaishno Devi',
    slug: 'vaishno-devi',
    region: 'Jammu & Kashmir',
    categoryTags: ['spiritual'],
    tagline: 'Holy Cave Shrine in the Trikuta Mountains',
    description: 'One of the most revered Shakti Peethas in the subcontinent, tucked inside a sanctified high-mountain cave in the Trikuta hills.',
    heroImage: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1600&q=85',
    thumbnail: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=600&q=80',
    bestTime: 'March to November',
    idealDuration: '3 Days',
    highlights: ['Holy Bhawan Cave Darshan', 'Trikuta Mountain Trail / Helicopter', 'Bhairon Baba Temple Ropeway', 'Katra Base Camp Concierge'],
  },
  {
    id: 'ayodhya',
    name: 'Ayodhya',
    slug: 'ayodhya',
    region: 'Uttar Pradesh',
    categoryTags: ['spiritual'],
    tagline: 'Ancient City of Shri Ram along the Holy Sarayu River',
    description: 'An epicenter of timeless epic lore, where the newly consecrated Shri Ram Janmabhoomi temple, Hanuman Garhi, and Sarayu river ghats welcome pilgrims.',
    heroImage: 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=1600&q=85',
    thumbnail: 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=600&q=80',
    bestTime: 'October to March',
    idealDuration: '2 Days',
    highlights: ['Shri Ram Janmabhoomi Mandir', 'Hanuman Garhi Fort Temple', 'Sarayu River Aarti at Ram Ki Paidi', 'Kanak Bhawan Royal Shrine'],
  },
  {
    id: 'varanasi',
    name: 'Varanasi',
    slug: 'varanasi',
    region: 'Uttar Pradesh',
    categoryTags: ['spiritual'],
    tagline: 'The Eternal City of Light on the Banks of the Sacred Ganges',
    description: 'One of the oldest continuously inhabited cities on Earth. Sunrise rowing past ancient stone bathing ghats, evening conch resonance, and Kashi Vishwanath blessings.',
    heroImage: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1600&q=85',
    thumbnail: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=600&q=80',
    bestTime: 'October to March',
    idealDuration: '2 to 3 Days',
    highlights: ['Dashashwamedh Ghat Grand Ganga Aarti', 'Sunrise Private Wooden Boat Ride', 'Kashi Vishwanath Corridor', 'Sarnath Buddha Enlightenment Site'],
  },
  {
    id: 'gaya-bodhgaya',
    name: 'Gaya–Bodhgaya',
    slug: 'gaya-bodhgaya',
    region: 'Bihar',
    categoryTags: ['spiritual'],
    tagline: 'The Bodhi Tree of Enlightenment & Ancestral Sacred Rites',
    description: 'Where Prince Siddhartha attained supreme enlightenment beneath the sacred Bodhi Tree. Bodhgaya hosts monasteries from Japan, Bhutan, and Thailand, alongside sacred Vishnupad in Gaya.',
    heroImage: 'https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&w=1600&q=85',
    thumbnail: 'https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&w=600&q=80',
    bestTime: 'October to March',
    idealDuration: '2 to 3 Days',
    highlights: ['Mahabodhi Temple Complex (UNESCO)', 'Sacred Bodhi Tree & Vajrasana', 'International Buddhist Monasteries', 'Vishnupad Temple on Falgu River'],
  },
];

export const PACKAGES: PackageTour[] = [
  {
    id: 'delhi-and-agra-4d3n',
    title: 'Delhi & Agra Tour',
    slug: 'delhi-and-agra-tour',
    duration: '4D / 3N',
    days: 4,
    nights: 3,
    route: 'Delhi → Agra → Fatehpur Sikri → Delhi',
    primaryDestinationTags: ['Delhi', 'Agra'],
    categories: ['heritage'],
    summary: 'A curated short break connecting the imperial capital of Delhi with the timeless sunrise grandeur of the Taj Mahal and Agra Fort.',
    heroImage: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1600&q=85',
    highlightTags: ['Sunrise Taj Mahal', 'Mughal Architecture', 'Private AC Vehicle', 'Expert Heritage Guides'],
    featured: true,
    operationalNotes: [
      'Taj Mahal Closure: The Taj Mahal remains closed to visitors on Fridays. We plan Day 3/Day 4 schedule accordingly.',
      'Monument Timing: A sunrise visit to the Taj Mahal is strongly recommended to avoid midday queues and heat.',
      'Drive Times: Delhi to Agra is approx. 3.5 hours (210 km) each way via the Yamuna Expressway.',
    ],
    inclusions: [
      'Private air-conditioned chauffeur-driven vehicle for all transfers and sightseeing',
      '3 Nights accommodation in handpicked heritage/boutique properties',
      'Daily breakfast at hotels',
      'Services of certified local monument guides in Delhi and Agra',
      'All toll taxes, interstate parking fees, and driver allowances',
      '24x7 dedicated trip concierge from Lobo Travels Delhi desk',
    ],
    exclusions: [
      'Monument entrance tickets (arranged directly on request without queues)',
      'Lunches, dinners, and personal beverages unless specified',
      'Camera/video fees at monuments',
      'Airfare/train tickets to and from Delhi',
      'Personal expenses, laundry, tipping, and travel insurance',
    ],
    faqs: [
      {
        question: 'When is the best time of year to take this Delhi & Agra tour?',
        answer: 'October through late March offers pleasant, cool weather ideal for monument exploration. Sunrise visits during these months are especially comfortable.',
      },
      {
        question: 'Can this itinerary be customized for an elderly traveler or young family?',
        answer: 'Absolutely. Every Lobo Travels itinerary is tailored individually. We can arrange battery carts at monuments, slower pacing, and flexible hotel choices.',
      },
      {
        question: 'What happens if our travel falls on a Friday when Taj Mahal is closed?',
        answer: 'Our travel desk proactively flips the sightseeing sequence so your visit to the Taj Mahal falls on Thursday or Saturday without missing a beat.',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Delhi & Ceremonial Boulevards',
        subheading: 'Arrival & Transfer',
        description: 'Warm welcome on arrival at Delhi Airport or Railway Station. Private transfer to your curated hotel. Following leisure and freshening up, embark on an evening drive past Kartavya Path, India Gate, and the illuminated facade of Rashtrapati Bhavan.',
        activities: [
          'Arrival at Delhi Airport / Railway Station with Lobo Travels chauffeur welcome',
          'Check-in, freshen up, and rest / leisure',
          'Evening sightseeing: India Gate & Kartavya Path promenade',
          'Drive past Rashtrapati Bhavan & Parliament House',
        ],
        meals: 'Breakfast at hotel on subsequent days',
        stay: 'Handpicked Deluxe / Boutique Hotel, Delhi',
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 2,
        title: 'Delhi Full-Day Sightseeing: Sandstone & Grandeur',
        subheading: 'Old & New Delhi Heritage Tour',
        description: 'Delve into centuries of history across Old and New Delhi. Marvel at the red sandstone fortifications of the Red Fort, pay homage at Raj Ghat, and stand beneath the soaring minaret of Qutub Minar. In the evening, visit the grand Akshardham Temple complex.',
        activities: [
          'Morning visit: Red Fort and Raj Ghat (Mahatma Gandhi Memorial)',
          'Afternoon exploration: UNESCO-listed Qutub Minar complex & Lotus Temple',
          'Evening experience: Akshardham Temple water-and-light show & cultural campus',
          'Free time for local culinary tasting or handicraft browsing',
        ],
        meals: 'Breakfast included',
        stay: 'Handpicked Deluxe / Boutique Hotel, Delhi',
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 3,
        title: 'Delhi to Agra via Yamuna Expressway & The Wonder of the World',
        subheading: 'Scenic Drive & Mughal Splendor',
        description: 'Depart Delhi after breakfast for a smooth drive along the Yamuna Expressway to Agra. Check into your hotel, then proceed to the breathtaking Taj Mahal, followed by the formidable ramparts of the Agra Fort overlooking the Yamuna River.',
        activities: [
          'Morning checkout and drive to Agra via Yamuna Expressway (approx. 3.5 hrs)',
          'Check-in at Agra hotel and refresh',
          'Afternoon / golden hour visit to the iconic Taj Mahal with private historian',
          'Explore Agra Fort: Diwan-i-Aam, Jahangiri Mahal, and Musamman Burj',
        ],
        meals: 'Breakfast included',
        stay: 'Handpicked Heritage / 4-5 Star Hotel, Agra',
        overnight: 'Overnight Stay: Agra',
      },
      {
        day: 4,
        title: 'Return to Delhi & Onward Departure',
        subheading: 'Smooth Return Transfer',
        description: 'Enjoy breakfast at leisure. Check out and embark on your return drive to Delhi along the expressway. Our chauffeur drops you safely at Delhi Airport or Railway Station for your flight/train home.',
        activities: [
          'Breakfast & check-out at Agra hotel',
          'Drive back to Delhi via Yamuna Expressway',
          'Drop-off at Delhi Airport / Railway Station for onward journey',
        ],
        meals: 'Breakfast included',
        stay: 'Departure / Tour Ends',
        overnight: 'Overnight Stay: Departure / Tour Ends',
      },
    ],
  },
  {
    id: 'delhi-agra-fatehpur-sikri-5d4n',
    title: 'Delhi, Agra & Fatehpur Sikri Tour',
    slug: 'delhi-agra-fatehpur-sikri-tour',
    duration: '5D / 4N',
    days: 5,
    nights: 4,
    route: 'Delhi → Agra → Fatehpur Sikri → Delhi',
    primaryDestinationTags: ['Delhi', 'Agra'],
    categories: ['heritage'],
    summary: 'An extended Mughal heritage circuit incorporating Akbar’s ghost city of Fatehpur Sikri, with leisurely pacing in both imperial capitals.',
    heroImage: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1600&q=85',
    highlightTags: ['Fatehpur Sikri', 'Buland Darwaza', 'Taj Mahal at Sunrise', 'Akshardham'],
    featured: false,
    operationalNotes: [
      'Taj Mahal Closure: Closed on Fridays; Day 3/Day 4 schedule avoids Friday for Taj visit.',
      'Fatehpur Sikri: Wear comfortable walking shoes; the sandstone courtyards are expansive.',
      'Drive Times: Delhi to Agra approx. 3.5 hours each way.',
    ],
    inclusions: [
      'Chauffeur-driven AC vehicle throughout all transfers and sightseeing',
      '4 Nights accommodation in handpicked boutique hotels',
      'Daily breakfast buffet',
      'Local certified heritage guides at Delhi, Agra, and Fatehpur Sikri',
      'All highway tolls, fuel, parking, and state permits',
    ],
    exclusions: [
      'Monument entrance tickets',
      'Meals other than breakfast',
      'Personal expenses & tipping',
    ],
    faqs: [
      {
        question: 'What is special about Fatehpur Sikri?',
        answer: 'Fatehpur Sikri was the short-lived capital built by Emperor Akbar in red sandstone. It features Buland Darwaza (the highest gateway in the world), Panch Mahal, and the white marble shrine of Sheikh Salim Chishti.',
      },
      {
        question: 'Can we add an extra night in Delhi or Agra?',
        answer: 'Yes! We customize every parameter. Simply let our concierge know when requesting your custom quote.',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Delhi',
        subheading: 'Arrival & Welcome',
        description: 'Pick-up from Delhi Airport / Railway Station and transfer to hotel. Evening sightseeing includes India Gate, Kartavya Path, and drive past Rashtrapati Bhavan.',
        activities: ['Pickup & check-in', 'Evening Kartavya Path walk', 'Drive past Rashtrapati Bhavan'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 2,
        title: 'Delhi Full-Day Sightseeing',
        subheading: 'Monuments of Power & Devotion',
        description: 'Visit Red Fort, Raj Ghat, Qutub Minar, and Lotus Temple. Evening visit to Akshardham Temple and time for boutique shopping.',
        activities: ['Red Fort & Raj Ghat', 'Qutub Minar & Lotus Temple', 'Akshardham Temple complex'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 3,
        title: 'Delhi to Agra',
        subheading: 'Yamuna Expressway to the City of Taj',
        description: 'Morning drive to Agra (approx. 3.5 hrs). Check in and visit the world-famous Taj Mahal and historic Agra Fort.',
        activities: ['Drive via Yamuna Expressway', 'Taj Mahal guided visit', 'Agra Fort exploration'],
        overnight: 'Overnight Stay: Agra',
      },
      {
        day: 4,
        title: 'Fatehpur Sikri Sightseeing & Return to Delhi',
        subheading: 'The Imperial Ghost Capital',
        description: 'Excursion to UNESCO World Heritage site Fatehpur Sikri to see Buland Darwaza, Panch Mahal, and Jodha Bai’s Palace. Return drive to Delhi.',
        activities: ['Fatehpur Sikri excursion', 'Drive back to Delhi', 'Check in at Delhi hotel'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 5,
        title: 'Delhi Departure',
        subheading: 'Farewell & Transfer',
        description: 'Breakfast and hotel check-out. Chauffeur drop to Airport or Railway Station for your onward journey.',
        activities: ['Check-out', 'Airport/Station transfer'],
        overnight: 'Overnight Stay: Departure / Tour Ends',
      },
    ],
  },
  {
    id: 'delhi-agra-mathura-vrindavan-4d3n',
    title: 'Delhi, Agra, Mathura & Vrindavan Tour',
    slug: 'delhi-agra-mathura-vrindavan-tour',
    duration: '4D / 3N',
    days: 4,
    nights: 3,
    route: 'Delhi → Mathura → Vrindavan → Agra → Delhi',
    primaryDestinationTags: ['Delhi', 'Agra', 'Mathura', 'Vrindavan'],
    categories: ['spiritual', 'heritage'],
    summary: 'A spiritually enriching journey blending Braj Bhoomi holy temples of Lord Krishna with Mughal architectural wonders.',
    heroImage: 'https://images.unsplash.com/photo-1621847468516-1ed5d0df56fe?auto=format&fit=crop&w=1600&q=85',
    highlightTags: ['Krishna Janmabhoomi', 'Prem Mandir Vrindavan', 'Taj Mahal Sunset', 'Akshardham'],
    featured: true,
    operationalNotes: [
      'Temple Timings: Mathura and Vrindavan temples generally close during afternoon hours (12:00 PM to 4:00 PM). We schedule morning and late afternoon visits.',
      'Dress Code: Standard modest dress code applies for temple visits in Mathura and Vrindavan.',
      'Taj Mahal Schedule: Closed on Fridays; itineraries are adjusted accordingly.',
    ],
    inclusions: [
      'Private air-conditioned vehicle throughout the entire 4-day tour',
      '3 Nights hotel accommodation (2N Delhi, 1N Agra)',
      'Daily breakfast at all hotels',
      'Temple coordination & local guides in Mathura, Vrindavan, and Agra',
      'All toll, parking, driver charges, and state taxes',
    ],
    exclusions: [
      'Temple donation tokens or VIP queue passes (can be arranged on request)',
      'Monument entrance fees',
      'Lunches & dinners',
    ],
    faqs: [
      {
        question: 'Are elderly pilgrims comfortably accommodated in Mathura-Vrindavan?',
        answer: 'Yes. We provide battery e-rickshaw transfers to inner temple streets where main cars cannot enter, ensuring effortless darshans.',
      },
      {
        question: 'What time is best to see Prem Mandir?',
        answer: 'Prem Mandir is best visited around twilight when its Italian marble facade is illuminated with shifting color lights and musical fountains.',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Delhi',
        subheading: 'Capital Welcome',
        description: 'Airport/Station pickup, check-in, and evening sightseeing of Kartavya Path, India Gate, and Rashtrapati Bhavan.',
        activities: ['Pickup & check-in', 'India Gate & Kartavya Path', 'Drive past Rashtrapati Bhavan'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 2,
        title: 'Delhi Full-Day Sightseeing',
        subheading: 'Mughal & Modern Icons',
        description: 'Full day tour of Red Fort & Jama Masjid, Raj Ghat, Qutub Minar, Lotus Temple, and Akshardham Temple in the evening.',
        activities: ['Red Fort & Jama Masjid', 'Qutub Minar & Lotus Temple', 'Akshardham Temple visit'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 3,
        title: 'Delhi to Mathura, Vrindavan & Agra',
        subheading: 'Sacred Braj Bhoomi to Mughal Agra',
        description: 'Morning drive to Mathura. Visit Shri Krishna Janmabhoomi Temple and Dwarkadhish Temple. Continue to Vrindavan to see Banke Bihari and Prem Mandir. In the afternoon, proceed to Agra, check in, visit Agra Fort and witness sunset at the Taj Mahal.',
        activities: [
          'Drive to Mathura (approx. 3 hrs via Yamuna Expressway)',
          'Shri Krishna Janmabhoomi Temple & Vishram Ghat',
          'Banke Bihari & Prem Mandir in Vrindavan',
          'Drive to Agra, Agra Fort, and Sunset Taj Mahal visit',
        ],
        overnight: 'Overnight Stay: Agra',
      },
      {
        day: 4,
        title: 'Return to Delhi & Departure',
        subheading: 'Expressway Return',
        description: 'Breakfast and check-out. Drive back to Delhi via Yamuna Expressway (approx. 3.5 hrs) and transfer to Airport / Railway Station.',
        activities: ['Breakfast & check-out', 'Drive to Delhi', 'Airport/Station drop-off'],
        overnight: 'Overnight Stay: Departure / Tour Ends',
      },
    ],
  },
  {
    id: 'delhi-agra-mathura-haridwar-rishikesh-7d6n',
    title: 'Delhi, Agra, Haridwar & Rishikesh Tour',
    slug: 'delhi-agra-haridwar-rishikesh-tour',
    duration: '7D / 6N',
    days: 7,
    nights: 6,
    route: 'Delhi → Agra (via Mathura & Vrindavan) → Delhi → Haridwar → Rishikesh → Delhi',
    primaryDestinationTags: ['Delhi', 'Agra', 'Haridwar–Rishikesh', 'Mathura', 'Vrindavan'],
    categories: ['spiritual', 'heritage'],
    summary: 'A seamless 7-day circuit fusing the architectural heights of Agra with the soulful holy waters of the Ganges at Haridwar and Rishikesh.',
    heroImage: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1600&q=85',
    highlightTags: ['Har Ki Pauri Aarti', 'Taj Mahal Day Trip', 'Rishikesh Ashrams', 'Braj Bhoomi'],
    featured: true,
    operationalNotes: [
      'Same-Day Logistics: Departure for Agra is scheduled early in the morning (around 5:30 AM – 6:00 AM) to comfortably cover Mathura, Vrindavan, Taj Mahal, and Agra Fort.',
      'Ganga Aarti Timing: Evening arrival at Har Ki Pauri should be scheduled 45 minutes prior to sunset for optimal viewing arrangements.',
      'Taj Mahal remains closed on Fridays.',
    ],
    inclusions: [
      'Private air-conditioned dedicated vehicle for all intercity transfers and excursions',
      '6 Nights accommodation in premium verified hotels',
      'Daily breakfast buffet',
      'Local destination specialists in Delhi, Agra, Haridwar, and Rishikesh',
      'Ropeway ticket assistance for Mansa Devi and Chandi Devi temples',
    ],
    exclusions: ['Monument and ropeway tickets', 'Meals other than breakfast', 'Personal items'],
    faqs: [
      {
        question: 'Can we attend both Haridwar and Rishikesh Ganga Aartis?',
        answer: 'Yes! On Day 4 you witness the electrifying grand Aarti at Har Ki Pauri, and on Day 5 you experience the serene musical Aarti at Triveni Ghat or Parmarth Niketan.',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Delhi',
        subheading: 'Capital Arrival',
        description: 'Airport/Station pickup, hotel transfer, and evening at leisure.',
        activities: ['Pickup & check-in', 'Evening rest'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 2,
        title: 'Delhi Sightseeing',
        subheading: 'Imperial Heritage Tour',
        description: 'Full day exploring Red Fort, Raj Ghat, Qutub Minar, Lotus Temple, and India Gate.',
        activities: ['Historic monuments', 'Rashtrapati Bhavan drive past'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 3,
        title: 'Same Day Agra Excursion (via Mathura & Vrindavan)',
        subheading: 'Taj Mahal & Holy Braj in a Single Day',
        description: 'Early morning start. Visit Krishna Janmabhoomi and Prem Mandir, proceed to Agra for Taj Mahal and Agra Fort, and return to Delhi in the evening.',
        activities: ['Early 5:30 AM departure', 'Mathura & Vrindavan temples', 'Taj Mahal & Agra Fort', 'Return to Delhi hotel'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 4,
        title: 'Delhi to Haridwar & Ganga Aarti',
        subheading: 'Spiritual Gateway to Garhwal',
        description: 'Morning drive from Delhi to holy Haridwar. Check in and visit Mansa Devi Temple via ropeway. In the evening, attend the legendary Ganga Aarti at Har Ki Pauri.',
        activities: ['Drive to Haridwar (approx. 4.5 hrs)', 'Mansa Devi & Chandi Devi ropeway', 'Har Ki Pauri Evening Aarti'],
        overnight: 'Overnight Stay: Haridwar',
      },
      {
        day: 5,
        title: 'Haridwar to Rishikesh Sightseeing',
        subheading: 'Yoga Capital & Sacred Footbridges',
        description: 'Short drive to Rishikesh. Cross Ram Jhula and Laxman Jhula, explore Parmarth Niketan and the Beatles Ashram, and witness the tranquil Aarti at Triveni Ghat.',
        activities: ['Ram Jhula & Laxman Jhula', 'Parmarth Niketan Ashram', 'Beatles Ashram', 'Triveni Ghat Evening Aarti'],
        overnight: 'Overnight Stay: Rishikesh',
      },
      {
        day: 6,
        title: 'Rishikesh to Delhi Return Transfer',
        subheading: 'Scenic Foothills Drive',
        description: 'Morning checkout and drive back to Delhi. Afternoon free for relaxation or Delhi bazaar shopping.',
        activities: ['Scenic drive back to Delhi', 'Check in and leisure'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 7,
        title: 'Departure from Delhi',
        subheading: 'Journey Concludes',
        description: 'Breakfast and transfer to Delhi Airport or Railway Station.',
        activities: ['Check-out and transfer'],
        overnight: 'Overnight Stay: Departure / Tour Ends',
      },
    ],
  },
  {
    id: 'golden-triangle-tour-6d5n',
    title: 'Golden Triangle Tour',
    slug: 'golden-triangle-tour',
    duration: '6D / 5N',
    days: 6,
    nights: 5,
    route: 'Delhi → Agra → Jaipur → Delhi',
    primaryDestinationTags: ['Delhi', 'Agra', 'Jaipur'],
    categories: ['heritage'],
    summary: 'India’s most celebrated cultural journey linking the political capital of Delhi, the romance of the Taj Mahal in Agra, and the royal pink sandstone splendor of Jaipur.',
    heroImage: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1600&q=85',
    highlightTags: ['Amber Fort Elephant/Jeep', 'Taj Mahal Sunrise', 'Fatehpur Sikri', 'City Palace & Hawa Mahal'],
    featured: true,
    operationalNotes: [
      'Taj Mahal Closure: Closed on Fridays. Our routing is calculated so Taj visits avoid Friday.',
      'Travel Times: Delhi to Agra ~3.5 hrs (Yamuna Expressway); Agra to Jaipur ~4.5–5 hrs (NH21 via Fatehpur Sikri); Jaipur to Delhi ~4.5–5 hrs (NH48).',
      'Jaipur Heritage: Amber Fort is best experienced in the early morning light.',
    ],
    inclusions: [
      'Dedicated AC Sedan / Innova Crysta for all 6 days',
      '5 Nights hotel accommodation in premier heritage/4-star properties',
      'Daily breakfast at all hotels',
      'Certified private local guides in Delhi, Agra, Fatehpur Sikri, and Jaipur',
      'All toll taxes, parking, driver allowance, and state border permits',
    ],
    exclusions: ['Monument entrance fees', 'Lunches and dinners', 'Jeep ride at Amber Fort (payable locally)'],
    faqs: [
      {
        question: 'Why is the Golden Triangle so famous?',
        answer: 'It forms a geographic triangle in North India that encapsulates three distinct architectural eras: Mughal emperors, Rajput royalty, and British colonial grandeur.',
      },
      {
        question: 'Can this tour end in Jaipur if we have a flight from there?',
        answer: 'Yes! We can drop you directly at Jaipur Airport or drive you back to Delhi according to your flight plans.',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Delhi',
        subheading: 'Welcome to India’s Capital',
        description: 'Airport/Station pickup and hotel check-in. Evening stroll along India Gate and Kartavya Path, with a drive past Rashtrapati Bhavan.',
        activities: ['Pickup & check-in', 'India Gate & Kartavya Path', 'Drive past Rashtrapati Bhavan'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 2,
        title: 'Delhi Full-Day Sightseeing',
        subheading: 'Historic Forts & Spiritual Centers',
        description: 'Visit Red Fort, Raj Ghat, Qutub Minar, and Lotus Temple. In the evening, explore Akshardham Temple.',
        activities: ['Red Fort & Raj Ghat', 'Qutub Minar & Lotus Temple', 'Akshardham Temple campus'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 3,
        title: 'Delhi to Agra: Sunrise & Citadel',
        subheading: 'Yamuna Expressway Drive',
        description: 'Drive to Agra. Check in and explore the Taj Mahal and Agra Fort.',
        activities: ['Drive to Agra via expressway', 'Taj Mahal guided visit', 'Agra Fort exploration'],
        overnight: 'Overnight Stay: Agra',
      },
      {
        day: 4,
        title: 'Agra to Jaipur via Fatehpur Sikri',
        subheading: 'Across Sandstone Gates into Royal Rajasthan',
        description: 'Depart Agra and stop at UNESCO ghost city Fatehpur Sikri (Buland Darwaza, Panch Mahal, Jodha Bai’s Palace). Proceed to Jaipur and check into your royal hotel.',
        activities: ['Fatehpur Sikri en-route excursion', 'Scenic drive to Jaipur', 'Evening at leisure in the Pink City'],
        overnight: 'Overnight Stay: Jaipur',
      },
      {
        day: 5,
        title: 'Jaipur Full-Day Royal Excursions',
        subheading: 'Amber Fort & Pink City Splendor',
        description: 'Ascend to Amber Fort and see Sheesh Mahal. Photo stop at water palace Jal Mahal. In the afternoon, visit City Palace, Jantar Mantar observatory, and Hawa Mahal.',
        activities: ['Amber Fort & Sheesh Mahal', 'Jal Mahal photo stop', 'City Palace & Jantar Mantar', 'Hawa Mahal Palace of Winds'],
        overnight: 'Overnight Stay: Jaipur',
      },
      {
        day: 6,
        title: 'Jaipur to Delhi & Departure',
        subheading: 'Return Drive & Homeward Bound',
        description: 'Breakfast and check-out. Drive back to Delhi via NH48 (lunch en-route) and drop at Delhi Airport or Railway Station.',
        activities: ['Scenic drive back to Delhi', 'Drop at Airport / Railway Station'],
        overnight: 'Overnight Stay: Departure / Tour Ends',
      },
    ],
  },
  {
    id: 'golden-triangle-leopard-safari-6d5n',
    title: 'Golden Triangle Tour (with Leopard Safari)',
    slug: 'golden-triangle-leopard-safari',
    duration: '6D / 5N',
    days: 6,
    nights: 5,
    route: 'Delhi → Agra → Jaipur → Delhi',
    primaryDestinationTags: ['Delhi', 'Agra', 'Jaipur'],
    categories: ['heritage', 'nature'],
    summary: 'An exclusive twist on the classic Golden Triangle, featuring an open-top gypsy safari through Jhalana Leopard Reserve right on the edge of the Pink City.',
    heroImage: 'https://images.unsplash.com/photo-1456926631375-92c8ce872def?auto=format&fit=crop&w=1600&q=85',
    highlightTags: ['Jhalana Leopard Safari', 'Taj Mahal', 'Amber Fort', 'Fatehpur Sikri'],
    featured: false,
    operationalNotes: [
      'Jhalana Safari slots are booked strictly in advance with Rajasthan Forest Department.',
      'Taj Mahal is closed on Fridays.',
    ],
    inclusions: [
      'Private AC vehicle throughout',
      'Exclusive 4x4 open gypsy safari booking at Jhalana with naturalist',
      '5 Nights hotel stay with breakfast',
      'Guides at all monuments',
    ],
    exclusions: ['Monument entry fees', 'Lunches & dinners'],
    faqs: [
      {
        question: 'What are the chances of spotting a leopard in Jhalana?',
        answer: 'Jhalana has one of the world’s highest densities of leopards per square kilometer, with sighting success rates exceeding 70% in dry months.',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Delhi',
        subheading: 'Arrival & Transfer',
        description: 'Airport/Station pickup, check-in, India Gate, and Rashtrapati Bhavan.',
        activities: ['Pickup & check-in', 'Evening India Gate drive'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 2,
        title: 'Delhi Full-Day Sightseeing',
        subheading: 'Capital Highlights',
        description: 'Red Fort, Raj Ghat, Qutub Minar, Lotus Temple, and Akshardham Temple.',
        activities: ['Historical sites', 'Temple visit'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 3,
        title: 'Delhi to Agra',
        subheading: 'Taj Mahal & Agra Fort',
        description: 'Expressway drive to Agra, check in and visit Taj Mahal and Agra Fort.',
        activities: ['Drive to Agra', 'Taj Mahal & Fort visit'],
        overnight: 'Overnight Stay: Agra',
      },
      {
        day: 4,
        title: 'Agra to Jaipur via Fatehpur Sikri & Evening Leopard Safari',
        subheading: 'Royal Sandstone into the Wild',
        description: 'Visit Fatehpur Sikri, drive to Jaipur, check in, and head out on the thrilling evening Jhalana Leopard Safari.',
        activities: ['Fatehpur Sikri', 'Check in Jaipur', 'Evening Jhalana Leopard Safari by open gypsy'],
        overnight: 'Overnight Stay: Jaipur',
      },
      {
        day: 5,
        title: 'Jaipur Full-Day Sightseeing',
        subheading: 'Palaces & Observatories',
        description: 'Amber Fort, Jal Mahal, City Palace, Jantar Mantar, and Hawa Mahal.',
        activities: ['Amber Fort', 'City Palace & Hawa Mahal'],
        overnight: 'Overnight Stay: Jaipur',
      },
      {
        day: 6,
        title: 'Jaipur to Delhi & Departure',
        subheading: 'Return Transfer',
        description: 'Drive back to Delhi and drop at Airport / Railway Station.',
        activities: ['Return drive to Delhi', 'Drop-off'],
        overnight: 'Overnight Stay: Departure / Tour Ends',
      },
    ],
  },
  {
    id: 'delhi-agra-shimla-manali-9d8n',
    title: 'Delhi, Agra, Shimla & Manali Tour',
    slug: 'delhi-agra-shimla-manali-tour',
    duration: '9D / 8N',
    days: 9,
    nights: 8,
    route: 'Delhi → Agra → Delhi → Shimla → Manali → Delhi / Chandigarh',
    primaryDestinationTags: ['Delhi', 'Agra', 'Shimla', 'Manali'],
    categories: ['nature', 'heritage'],
    summary: 'The ultimate grand North India itinerary uniting Mughal architectural wonders with the snow peaks, apple valleys, and colonial ridges of Himachal Pradesh.',
    heroImage: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1600&q=85',
    highlightTags: ['Taj Mahal & Agra Fort', 'Solang Valley Snow', 'The Ridge Shimla', 'Kullu River Rafting'],
    featured: true,
    operationalNotes: [
      'Agra Same-Day Travel: Uses Yamuna Expressway for optimal travel times (approx. 3.5 to 4 hours each way).',
      'Adventure & Hill Driving: Solang Valley activities and Kullu river rafting remain subject to weather/seasonal guidelines.',
      'Flexible return drop available for both Delhi or Chandigarh.',
    ],
    inclusions: [
      'Private dedicated vehicle for the entire 9-day circuit with hill-certified chauffeur',
      '8 Nights verified accommodation (3N Delhi, 2N Shimla, 3N Manali)',
      'Daily breakfast at all hotels',
      'Sightseeing across Delhi, Agra, Shimla, Kullu, and Manali',
    ],
    exclusions: ['Adventure activities fees', 'Monument entrance tickets', 'Lunches & dinners'],
    faqs: [
      {
        question: 'Is it better to fly out of Chandigarh or Delhi on Day 9?',
        answer: 'Chandigarh Airport is much closer to Manali, saving ~4-5 hours of drive time. We can drop you at either airport at no extra charge.',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Delhi',
        subheading: 'Arrival & Welcome',
        description: 'Pickup from Delhi Airport or Railway Station, hotel check-in, and evening at leisure.',
        activities: ['Airport pickup', 'Check-in and leisure'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 2,
        title: 'Delhi Sightseeing',
        subheading: 'Monuments of Delhi',
        description: 'Red Fort, Raj Ghat, Qutub Minar, Lotus Temple, India Gate, and Rashtrapati Bhavan area.',
        activities: ['Old & New Delhi sightseeing'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 3,
        title: 'Delhi to Agra Excursion & Return',
        subheading: 'Same-Day Taj Mahal Wonder',
        description: 'Early morning expressway drive to Agra. Marvel at the Taj Mahal and Agra Fort, returning to Delhi by evening.',
        activities: ['Yamuna Expressway drive', 'Taj Mahal & Agra Fort', 'Return drive to Delhi'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 4,
        title: 'Delhi to Shimla & Mall Road Evening',
        subheading: 'Ascent to the Pine Hills',
        description: 'Drive from Delhi up into the Himalayan foothills to Shimla. Check into your hotel and enjoy an evening stroll along Mall Road, The Ridge, and Scandal Point.',
        activities: ['Scenic drive to Shimla', 'Evening on Mall Road & The Ridge'],
        overnight: 'Overnight Stay: Shimla',
      },
      {
        day: 5,
        title: 'Shimla Sightseeing & Kufri Panorama',
        subheading: 'Colonial Vistas & Alpine Ridge',
        description: 'Excursion to Kufri for panoramic Himalayan views. Return to Shimla to visit Christ Church and optional Jakhoo Temple.',
        activities: ['Kufri excursion', 'Christ Church & Gaiety Theatre', 'Jakhoo Temple'],
        overnight: 'Overnight Stay: Shimla',
      },
      {
        day: 6,
        title: 'Shimla to Manali via Kullu Valley',
        subheading: 'Beas River Vistas & Handloom Ateliers',
        description: 'Drive along the turquoise Beas River. Stop at Kullu Valley for shawl weaving and optional white water rafting. Arrive in Manali.',
        activities: ['Kullu Valley scenic drive', 'Kullu Shawl centre', 'Optional river rafting', 'Check in Manali'],
        overnight: 'Overnight Stay: Manali',
      },
      {
        day: 7,
        title: 'Manali Sightseeing & Solang Valley',
        subheading: 'Alpine Splendor & Ancient Temples',
        description: 'Excursion to Solang Valley for mountain views and paragliding/snow activities. Later, visit ancient Hadimba Devi wood temple, Vashisht hot springs, and Mall Road.',
        activities: ['Solang Valley alpine adventure', 'Hadimba Devi Temple', 'Vashisht hot springs', 'Mall Road stroll'],
        overnight: 'Overnight Stay: Manali',
      },
      {
        day: 8,
        title: 'Manali to Delhi / Chandigarh',
        subheading: 'Descent from the Hills',
        description: 'Drive downhill from Manali toward Delhi or Chandigarh with scenic stops. Check in and enjoy a relaxing evening.',
        activities: ['Descent drive through valleys', 'Hotel check-in and evening rest'],
        overnight: 'Overnight Stay: Delhi / Chandigarh',
      },
      {
        day: 9,
        title: 'Departure Transfer',
        subheading: 'Farewell Himalayas',
        description: 'Hotel check-out and chauffeur drop to Delhi or Chandigarh Airport/Station.',
        activities: ['Transfer to Airport / Railway Station'],
        overnight: 'Overnight Stay: Departure / Tour Ends',
      },
    ],
  },
  {
    id: 'delhi-shimla-manali-8d7n',
    title: 'Delhi, Shimla & Manali Tour',
    slug: 'delhi-shimla-manali-tour',
    duration: '8D / 7N',
    days: 8,
    nights: 7,
    route: 'Delhi → Shimla → Manali → Delhi / Chandigarh',
    primaryDestinationTags: ['Delhi', 'Shimla', 'Manali'],
    categories: ['nature', 'honeymoon'],
    summary: 'A classic 8-day Himalayan escape through pine forests, apple orchards, and snow-clad mountains of Himachal Pradesh.',
    heroImage: 'https://images.unsplash.com/photo-1597074866923-dc0589150358?auto=format&fit=crop&w=1600&q=85',
    highlightTags: ['Solang Valley', 'Kufri Snow View', 'Mall Road Shimla', 'Hadimba Temple'],
    featured: false,
    operationalNotes: [
      'Flexible Pickup/Drop: Day 1 pickup and Day 8 drop-off can be aligned with Delhi Airport or any major Delhi/Chandigarh Station.',
      'Solang Valley and Kullu river rafting are subject to local weather conditions.',
    ],
    inclusions: [
      'Private vehicle with mountain-experienced driver',
      '7 Nights accommodation in deluxe mountain-view hotels',
      'Daily breakfast',
      'Local sightseeing in Delhi, Shimla, Kullu, and Manali',
    ],
    exclusions: ['Adventure activity fees', 'Monument entries', 'Meals not specified'],
    faqs: [
      {
        question: 'Is snow guaranteed in Solang Valley?',
        answer: 'Snow is typically present from December to March in Solang and Rohtang Pass. During other months, Solang is lush green with paragliding and zorbing.',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Delhi',
        subheading: 'Arrival & Welcome',
        description: 'Pickup from Delhi Airport or Station and check-in. Evening at leisure.',
        activities: ['Pickup & check-in'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 2,
        title: 'Delhi Sightseeing',
        subheading: 'Capital City Tour',
        description: 'Red Fort, Raj Ghat, Qutub Minar, Lotus Temple, India Gate, and Rashtrapati Bhavan.',
        activities: ['Full-day city tour'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 3,
        title: 'Delhi to Shimla & Mall Road Evening',
        subheading: 'Scenic Hill Climb',
        description: 'Drive from Delhi to Shimla. Evening stroll along Mall Road, The Ridge, and Scandal Point.',
        activities: ['Drive to Shimla', 'Mall Road evening stroll'],
        overnight: 'Overnight Stay: Shimla',
      },
      {
        day: 4,
        title: 'Shimla Sightseeing & Kufri',
        subheading: 'Pine Woods & Christ Church',
        description: 'Visit Kufri, Christ Church, and optional Jakhoo Temple.',
        activities: ['Kufri excursion', 'Christ Church visit'],
        overnight: 'Overnight Stay: Shimla',
      },
      {
        day: 5,
        title: 'Shimla to Manali via Kullu',
        subheading: 'Beas Valley Drive',
        description: 'Drive through Kullu Valley. Visit Kullu Shawl centre, optional rafting, arrive in Manali.',
        activities: ['Kullu Valley drive', 'Handloom visit'],
        overnight: 'Overnight Stay: Manali',
      },
      {
        day: 6,
        title: 'Manali Sightseeing & Solang Valley',
        subheading: 'High Altitude Panorama',
        description: 'Solang Valley mountain excursion, Hadimba Devi temple, Vashisht springs, and Tibetan Monastery.',
        activities: ['Solang Valley', 'Hadimba Temple & hot springs'],
        overnight: 'Overnight Stay: Manali',
      },
      {
        day: 7,
        title: 'Manali to Delhi / Chandigarh',
        subheading: 'Return Downhill Transfer',
        description: 'Drive down from Manali toward Delhi or Chandigarh, check in and relax.',
        activities: ['Scenic valley drive'],
        overnight: 'Overnight Stay: Delhi / Chandigarh',
      },
      {
        day: 8,
        title: 'Departure Transfer',
        subheading: 'Onward Journey',
        description: 'Transfer and drop to Delhi or Chandigarh Airport / Station.',
        activities: ['Airport/Station drop-off'],
        overnight: 'Overnight Stay: Departure / Tour Ends',
      },
    ],
  },
  {
    id: 'delhi-amritsar-manali-shimla-9d8n',
    title: 'Delhi, Amritsar, Manali & Shimla Tour',
    slug: 'delhi-amritsar-manali-shimla-tour',
    duration: '9D / 8N',
    days: 9,
    nights: 8,
    route: 'Delhi → Amritsar → Manali → Shimla → Delhi',
    primaryDestinationTags: ['Delhi', 'Amritsar', 'Manali', 'Shimla'],
    categories: ['heritage', 'spiritual', 'nature'],
    summary: 'A grand northern tapestry featuring the sacred Golden Temple and Wagah Border ceremony, followed by the alpine serenity of Manali and Shimla.',
    heroImage: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&w=1600&q=85',
    highlightTags: ['Golden Temple Amritsar', 'Wagah Border Beating Retreat', 'Solang Valley', 'Shimla Kufri'],
    featured: true,
    operationalNotes: [
      'Wagah Border Protocol: Carry original government photo IDs for entry at Wagah Border. Advise clients to avoid carrying large bags due to security.',
      'Long Overland Sectors: Delhi to Amritsar (~450 km) and Amritsar to Manali (~400 km) are full-day driving routes; we schedule early morning starts.',
      'Adventure Activities: Solang Valley and Kullu river rafting are subject to local weather.',
    ],
    inclusions: [
      'Private luxury vehicle with seasoned highway & hill driver',
      '8 Nights hotel accommodation in premier properties',
      'Daily breakfast',
      'Guided tour of Golden Temple, Wagah border assistance, and hill stations',
    ],
    exclusions: ['Wagah VIP permits (free seating assistance provided)', 'Lunches & dinners'],
    faqs: [
      {
        question: 'What time does the Wagah Border ceremony begin?',
        answer: 'The Beating Retreat ceremony begins around 4:30 PM in winter and 5:30 PM in summer. We arrive by 3:00 PM – 3:30 PM for prime seats.',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Delhi',
        subheading: 'Capital Welcome',
        description: 'Pickup from Delhi Airport or Station and hotel check-in. Evening at leisure.',
        activities: ['Pickup & check-in', 'Evening leisure'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 2,
        title: 'Delhi to Amritsar | Wagah Border',
        subheading: 'Journey to the Land of the Gurus',
        description: 'Early morning drive to Amritsar. In the afternoon, travel to the Wagah-Attari Border to attend the electrifying Beating Retreat Ceremony.',
        activities: ['Early drive to Amritsar', 'Wagah Border Beating Retreat Ceremony', 'Check in at Amritsar hotel'],
        overnight: 'Overnight Stay: Amritsar',
      },
      {
        day: 3,
        title: 'Amritsar to Manali',
        subheading: 'Golden Temple Darshan & Hill Climb',
        description: 'Morning visit to the serene Golden Temple and historic Jallianwala Bagh. Embark on the picturesque drive into the mountains toward Manali.',
        activities: ['Golden Temple & Jallianwala Bagh', 'Scenic drive into Himachal', 'Check-in at Manali hotel'],
        overnight: 'Overnight Stay: Manali',
      },
      {
        day: 4,
        title: 'Manali Sightseeing & Solang Valley',
        subheading: 'High Mountain Vistas',
        description: 'Drive to Solang Valley for alpine surroundings and optional adventure. Evening visit to Hadimba Devi Temple, Vashisht springs, and Mall Road.',
        activities: ['Solang Valley mountain excursion', 'Hadimba Temple & Vashisht springs', 'Mall Road stroll'],
        overnight: 'Overnight Stay: Manali',
      },
      {
        day: 5,
        title: 'Manali to Shimla via Kullu',
        subheading: 'River Valleys & Craft Centers',
        description: 'Transfer via Kullu Valley, scenic Beas riverbanks, local shawl center, and optional river rafting. Continue to Shimla.',
        activities: ['Kullu exploration & shawl weaving', 'Optional river rafting', 'Arrive and check in Shimla'],
        overnight: 'Overnight Stay: Shimla',
      },
      {
        day: 6,
        title: 'Shimla Sightseeing',
        subheading: 'The Ridge & Kufri',
        description: 'Excursion to Kufri, visit The Ridge, Christ Church, Scandal Point, and optional Jakhoo Temple.',
        activities: ['Kufri panorama', 'Christ Church & Mall Road'],
        overnight: 'Overnight Stay: Shimla',
      },
      {
        day: 7,
        title: 'Shimla to Delhi',
        subheading: 'Return Transfer',
        description: 'Early morning check-out and drive from Shimla back to Delhi. Lunch break en-route. Check in Delhi hotel.',
        activities: ['Drive to Delhi', 'Check in and evening rest'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 8,
        title: 'Delhi Sightseeing',
        subheading: 'Capital Finale',
        description: 'Full day city sightseeing: Red Fort, Raj Ghat, Qutub Minar, Lotus Temple, India Gate, and Rashtrapati Bhavan.',
        activities: ['Red Fort & Qutub Minar', 'India Gate promenade'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 9,
        title: 'Departure from Delhi',
        subheading: 'Tour Concludes',
        description: 'Checkout and drop to Delhi Airport / Railway station.',
        activities: ['Transfer to Airport / Station'],
        overnight: 'Overnight Stay: Departure / Tour Ends',
      },
    ],
  },
  {
    id: 'delhi-amritsar-dalhousie-dharamshala-9d8n',
    title: 'Delhi, Amritsar, Dalhousie & Dharamshala Tour',
    slug: 'delhi-amritsar-dalhousie-dharamshala-tour',
    duration: '9D / 8N',
    days: 9,
    nights: 8,
    route: 'Delhi → Amritsar → Dalhousie → Dharamshala → Chandigarh / Delhi',
    primaryDestinationTags: ['Delhi', 'Amritsar', 'Dalhousie', 'Dharamshala'],
    categories: ['heritage', 'spiritual', 'nature'],
    summary: 'A breathtaking route across the Golden Temple, Khajjiar’s mini-Switzerland meadows, and the serene Tibetan monasteries of McLeod Ganj.',
    heroImage: 'https://images.unsplash.com/photo-1506461883276-594a12b11cf3?auto=format&fit=crop&w=1600&q=85',
    highlightTags: ['Khajjiar Meadow', 'Dalai Lama Temple', 'Golden Temple', 'Bhagsu Waterfall'],
    featured: false,
    operationalNotes: [
      'Wagah Border Ceremony: Reaching Attari-Wagah Border by 3:00 PM – 3:30 PM is recommended.',
      'Flexible Return Drop: Options provided for both Chandigarh and Delhi.',
    ],
    inclusions: [
      'Private AC vehicle for 9 days with professional chauffeur',
      '8 Nights hotel accommodation with daily breakfast',
      'Excursion to Khajjiar meadow and lake',
      'Local sightseeing in Amritsar, Dalhousie, and McLeod Ganj',
    ],
    exclusions: ['Monument fees', 'Lunches & dinners'],
    faqs: [
      {
        question: 'Why is Khajjiar called Mini Switzerland of India?',
        answer: 'Swiss Ambassador Willy P. Blazer officially gave Khajjiar that title due to its striking topographical resemblance to Swiss pine meadows and saucer-shaped lake.',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Delhi',
        subheading: 'Arrival & Welcome',
        description: 'Pickup from Delhi Airport or Station, hotel check-in, evening at leisure.',
        activities: ['Pickup & check-in'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 2,
        title: 'Delhi Sightseeing',
        subheading: 'Full-Day City Tour',
        description: 'Red Fort, Raj Ghat, Qutub Minar, Lotus Temple, India Gate, and Rashtrapati Bhavan.',
        activities: ['City monuments tour'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 3,
        title: 'Delhi to Amritsar | Wagah Border',
        subheading: 'Drive to Punjab & Border Ceremony',
        description: 'Early morning drive to Amritsar. Visit Wagah Border for the Beating Retreat Ceremony.',
        activities: ['Drive to Amritsar', 'Wagah Border ceremony'],
        overnight: 'Overnight Stay: Amritsar',
      },
      {
        day: 4,
        title: 'Amritsar Sightseeing to Dalhousie',
        subheading: 'Golden Temple to Colonial Pine Ridge',
        description: 'Morning visit to Jallianwala Bagh and Golden Temple. Drive to Dalhousie, check in, and stroll along Mall Road and Subhash Chowk.',
        activities: ['Golden Temple & Jallianwala Bagh', 'Drive to Dalhousie', 'Mall Road evening stroll'],
        overnight: 'Overnight Stay: Dalhousie',
      },
      {
        day: 5,
        title: 'Dalhousie & Khajjiar Sightseeing',
        subheading: 'Mini Switzerland of India',
        description: 'Excursion to Khajjiar alpine meadow and Khajji Nag Temple. Visit Panchpula, Satdhara Falls, and scenic Bakrota Hills.',
        activities: ['Khajjiar meadow excursion', 'Panchpula & Satdhara Falls', 'Bakrota Hills views'],
        overnight: 'Overnight Stay: Dalhousie',
      },
      {
        day: 6,
        title: 'Dalhousie to Dharamshala / McLeod Ganj',
        subheading: 'Into the Kangra Valley',
        description: 'Drive to McLeod Ganj. Check in and visit Tsuglagkhang Complex (Dalai Lama Temple) and St. John in the Wilderness Church.',
        activities: ['Drive to Dharamshala', 'Tsuglagkhang Complex', 'St. John in the Wilderness Church'],
        overnight: 'Overnight Stay: Dharamshala / McLeod Ganj',
      },
      {
        day: 7,
        title: 'Dharamshala & McLeod Ganj Sightseeing',
        subheading: 'Tibetan Arts & Waterfalls',
        description: 'Bhagsu Nag Temple and waterfall, Tibetan Museum, Norbulingka Institute, and evening stroll through McLeod Ganj local market.',
        activities: ['Bhagsu Waterfall & Temple', 'Norbulingka Institute & Museum', 'Tibetan market handicrafts'],
        overnight: 'Overnight Stay: Dharamshala / McLeod Ganj',
      },
      {
        day: 8,
        title: 'Dharamshala to Delhi / Chandigarh',
        subheading: 'Return Transfer',
        description: 'Morning drive toward Chandigarh or Delhi. Check in and rest.',
        activities: ['Scenic downhill drive', 'Hotel check-in'],
        overnight: 'Overnight Stay: Delhi / Chandigarh',
      },
      {
        day: 9,
        title: 'Departure Transfer',
        subheading: 'Homeward Bound',
        description: 'Check out and transfer to Delhi / Chandigarh Airport or Railway Station.',
        activities: ['Transfer to Airport / Station'],
        overnight: 'Overnight Stay: Departure / Tour Ends',
      },
    ],
  },
  {
    id: 'delhi-haridwar-dehradun-mussoorie-8d7n',
    title: 'Delhi, Haridwar, Dehradun & Mussoorie Tour',
    slug: 'delhi-haridwar-dehradun-mussoorie-tour',
    duration: '8D / 7N',
    days: 8,
    nights: 7,
    route: 'Delhi → Haridwar → Rishikesh → Dehradun → Mussoorie → Delhi',
    primaryDestinationTags: ['Delhi', 'Haridwar–Rishikesh', 'Mussoorie', 'Dehradun'],
    categories: ['nature', 'spiritual'],
    summary: 'A rejuvenating blend of sacred river aartis, lush Doon valley greenery, and Mussoorie’s colonial hill promenades.',
    heroImage: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=1600&q=85',
    highlightTags: ['Har Ki Pauri Aarti', 'Kempty Falls', 'Gun Hill Cable Car', 'Robber’s Cave'],
    featured: false,
    operationalNotes: [
      'Rishikesh Integration: A scenic stopover at Rishikesh is included between Haridwar and Dehradun.',
      'Ganga Aarti Timing: Arrival at Har Ki Pauri should be 45 minutes prior to sunset.',
    ],
    inclusions: [
      'Dedicated AC vehicle throughout',
      '7 Nights accommodation in curated hotels',
      'Daily breakfast buffet',
      'Sightseeing in Delhi, Haridwar, Rishikesh, Dehradun, and Mussoorie',
    ],
    exclusions: ['Cable car & monument tickets', 'Lunches & dinners'],
    faqs: [
      {
        question: 'What is Robber’s Cave (Guchhupani) in Dehradun?',
        answer: 'It is a natural limestone river cave where cold water flows ankle-deep through a narrow gorge, creating a thrilling walk beneath dripping rock overhangs.',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Delhi',
        subheading: 'Arrival & Welcome',
        description: 'Pickup from Delhi Airport or Station and hotel check-in. Evening at leisure.',
        activities: ['Pickup & check-in'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 2,
        title: 'Delhi Sightseeing',
        subheading: 'Capital Landmarks',
        description: 'Red Fort, Raj Ghat, Qutub Minar, Lotus Temple, India Gate, and Rashtrapati Bhavan.',
        activities: ['Capital monuments'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 3,
        title: 'Delhi to Haridwar & Ganga Aarti',
        subheading: 'Sacred Ganga Ghats',
        description: 'Drive to Haridwar. Visit Mansa Devi and Chandi Devi temples. In the evening, attend the legendary Ganga Aarti at Har Ki Pauri.',
        activities: ['Drive to Haridwar', 'Temple visits', 'Har Ki Pauri Aarti'],
        overnight: 'Overnight Stay: Haridwar',
      },
      {
        day: 4,
        title: 'Haridwar to Rishikesh Excursion to Dehradun',
        subheading: 'Suspension Bridges to Doon Valley',
        description: 'Short drive to Rishikesh for Ram Jhula, Laxman Jhula, Triveni Ghat, and Parmarth Niketan. Proceed to Dehradun and check in.',
        activities: ['Rishikesh bridges & ashrams', 'Drive to Dehradun'],
        overnight: 'Overnight Stay: Dehradun',
      },
      {
        day: 5,
        title: 'Dehradun Sightseeing to Mussoorie',
        subheading: 'Robber’s Cave & The Queen of the Hills',
        description: 'Visit Robber’s Cave (Guchhupani), Sahastradhara, and Mindrolling Monastery. Scenic afternoon drive up to Mussoorie; check in and stroll Mall Road.',
        activities: ['Robber’s Cave & Mindrolling Monastery', 'Scenic climb to Mussoorie', 'Mall Road stroll'],
        overnight: 'Overnight Stay: Mussoorie',
      },
      {
        day: 6,
        title: 'Mussoorie Full-Day Sightseeing',
        subheading: 'Waterfalls & Himalayan Views',
        description: 'Visit Kempty Falls, take the cable car to Gun Hill for 360-degree Himalayan vistas, and walk Camel’s Back Road.',
        activities: ['Kempty Falls', 'Gun Hill cable car', 'Camel’s Back Road'],
        overnight: 'Overnight Stay: Mussoorie',
      },
      {
        day: 7,
        title: 'Mussoorie to Delhi Return Transfer',
        subheading: 'Descent & Return',
        description: 'Check out and drive back to Delhi with scenic stops. Check in and relax.',
        activities: ['Drive to Delhi', 'Check in Delhi'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 8,
        title: 'Departure Transfer',
        subheading: 'Journey Concludes',
        description: 'Transfer to Delhi Airport or Station for onward flight/train.',
        activities: ['Airport/Station drop-off'],
        overnight: 'Overnight Stay: Departure / Tour Ends',
      },
    ],
  },
  {
    id: 'delhi-haridwar-nainital-bhimtal-8d7n',
    title: 'Delhi, Haridwar, Nainital & Bhimtal Tour',
    slug: 'delhi-haridwar-nainital-bhimtal-tour',
    duration: '8D / 7N',
    days: 8,
    nights: 7,
    route: 'Delhi → Haridwar → Nainital → Bhimtal → Delhi / Chandigarh',
    primaryDestinationTags: ['Delhi', 'Haridwar–Rishikesh', 'Nainital', 'Bhimtal'],
    categories: ['nature', 'spiritual'],
    summary: 'From the sacred evening aartis of Haridwar to the tranquil shimmering lakes and pine forests of Nainital, Bhimtal, and Sattal.',
    heroImage: 'https://images.unsplash.com/photo-1610484826967-09c5720778c7?auto=format&fit=crop&w=1600&q=85',
    highlightTags: ['Naini Lake Boating', 'Har Ki Pauri Aarti', 'Bhimtal Island Aquarium', 'Snow View Point'],
    featured: false,
    operationalNotes: [
      'Lake District Boating: Boating and water activities at Bhimtal and Naukuchiatal are weather-dependent.',
      'Route Alignment: Seamlessly connects Garhwal (Haridwar) with the Kumaon Lake Circuit.',
    ],
    inclusions: [
      'Private dedicated vehicle with experienced Kumaon hills driver',
      '7 Nights accommodation in handpicked lakeview & boutique hotels',
      'Daily breakfast',
      'Boat ride coordination on Naini Lake and Bhimtal',
    ],
    exclusions: ['Boating & ropeway fees', 'Monument entries', 'Lunches & dinners'],
    faqs: [
      {
        question: 'Which is quieter, Nainital or Bhimtal?',
        answer: 'Bhimtal is far more peaceful and unhurried than bustling Nainital. This itinerary gives you the vibrant buzz of Nainital plus the tranquil lakeside quiet of Bhimtal.',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Delhi',
        subheading: 'Capital Welcome',
        description: 'Pickup from Delhi Airport or Station, check in and evening at leisure.',
        activities: ['Pickup & check-in'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 2,
        title: 'Delhi Sightseeing',
        subheading: 'City Highlights',
        description: 'Red Fort, Raj Ghat, Qutub Minar, Lotus Temple, and India Gate.',
        activities: ['Full-day sightseeing'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 3,
        title: 'Delhi to Haridwar & Ganga Aarti',
        subheading: 'Sacred Gateway',
        description: 'Drive to Haridwar, visit Mansa Devi & Chandi Devi, and attend Har Ki Pauri Ganga Aarti.',
        activities: ['Drive to Haridwar', 'Temple visits', 'Har Ki Pauri Aarti'],
        overnight: 'Overnight Stay: Haridwar',
      },
      {
        day: 4,
        title: 'Haridwar to Nainital via Corbett Foothills',
        subheading: 'Scenic Drive into Kumaon',
        description: 'Morning drive along the Shivalik hills up to Nainital. Check in, enjoy an evening boat ride on Naini Lake, and stroll Mall Road.',
        activities: ['Scenic drive to Nainital', 'Naini Lake boat ride', 'Mall Road evening stroll'],
        overnight: 'Overnight Stay: Nainital',
      },
      {
        day: 5,
        title: 'Nainital Sightseeing & Peak Views',
        subheading: 'Himalayan Vistas & Caves',
        description: 'Visit Naina Devi Temple, take the aerial ropeway to Snow View Point, and explore Eco Cave Gardens and Tibetan Market.',
        activities: ['Naina Devi Temple', 'Snow View aerial ropeway', 'Eco Cave Gardens'],
        overnight: 'Overnight Stay: Nainital',
      },
      {
        day: 6,
        title: 'Nainital to Lake Tour (Bhimtal, Sattal, Naukuchiatal)',
        subheading: 'Kumaon Lake Circuit',
        description: 'Drive to Bhimtal. Visit Bhimtal Lake with its island aquarium, explore Sattal’s seven interconnected lakes, and visit Naukuchiatal. Relax by Bhimtal lake.',
        activities: ['Bhimtal Lake & Island Aquarium', 'Sattal forest lakes', 'Naukuchiatal nine-cornered lake'],
        overnight: 'Overnight Stay: Bhimtal',
      },
      {
        day: 7,
        title: 'Bhimtal to Delhi Return Transfer',
        subheading: 'Descent to Capital',
        description: 'Scenic downhill drive back to Delhi. Check in and relax.',
        activities: ['Drive to Delhi', 'Check in Delhi hotel'],
        overnight: 'Overnight Stay: Delhi',
      },
      {
        day: 8,
        title: 'Departure Transfer',
        subheading: 'Tour Concludes',
        description: 'Check out and transfer to Delhi Airport or Station for onward journey.',
        activities: ['Airport/Station drop-off'],
        overnight: 'Overnight Stay: Departure / Tour Ends',
      },
    ],
  },
];

export const TESTIMONIALS = [
  {
    id: '1',
    quote: 'Most Indian travel portals gave me automated 3-star package rates. Lobo Travels assigned a dedicated trip designer who spoke with us, curated a private Taj Mahal sunrise and luxury Jaipur haveli, and our chauffeur was impeccable throughout.',
    author: 'Vikram & Radhika Singhania',
    location: 'Mumbai',
    trip: 'Golden Triangle Tour (6D/5N), October 2025',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: '2',
    quote: 'Taking my elderly parents to Haridwar and Rishikesh felt daunting until Lobo Travels took over. From seamless wheelchair assistance at Har Ki Pauri to tranquil riverside stays, every detail was handled with genuine empathy and precision.',
    author: 'Dr. Anandita Sharma',
    location: 'Bengaluru',
    trip: 'Delhi, Haridwar & Rishikesh Spiritual Circuit, December 2025',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: '3',
    quote: 'Our honeymoon in Kashmir was flawless. Private shikara on Dal Lake at dusk, heating pre-arranged in our cottage at Gulmarg, and a driver who felt like family. Lobo Travels represents the gold standard of customized travel.',
    author: 'Rohan & Meera Verma',
    location: 'New Delhi',
    trip: 'Kashmir Honeymoon Special, January 2026',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
  },
];

export const WHY_CHOOSE_US = [
  {
    icon: 'Sparkles',
    title: '100% Curated Around You',
    description: 'We don’t sell off-the-shelf fixed boxes. Every day, halt, and hotel is chosen around your rhythm, interests, and dietary preferences.',
  },
  {
    icon: 'PhoneCall',
    title: '24x7 On-Trip Concierge',
    description: 'A direct WhatsApp helpline and dedicated desk officer in Mandir Marg watching over your transfers in real time, from touchdown to departure.',
  },
  {
    icon: 'ShieldCheck',
    title: 'Handpicked Verified Stays',
    description: 'Every boutique haveli, alpine resort, and heritage property is personally audited for hygiene, location, comfort, and authentic hospitality.',
  },
  {
    icon: 'Users',
    title: 'Certified Local Guides',
    description: 'We pair you with passionate, government-licensed local historians and naturalists who bring stories and hidden corners to life.',
  },
  {
    icon: 'CreditCard',
    title: 'Transparent Quotations',
    description: 'We don’t paste fake teaser prices. You get clear, itemized proposals with zero hidden toll, fuel, or parking surprises.',
  },
];
